### PR TITLE
wallet: fix broken sync logic where multiple blocks are needed

### LINKED ISSUE #199: CUSF enforcer task w/o mempool: failed connecting block to BDK chain
During initial sync - when syncing the chain in parallell with bitcoin core - the enforcer crashes with the error message `CUSF enforcer task w/o mempool: failed connecting block to BDK chain`. A simple restart makes it chug on.

The final log before the crash:
```
2025-04-28T05:00:49.800751Z  INFO wallet_sync:handle_connect_block: bip300301_enforcer_lib::wallet::sync: lib/wallet/sync.rs:78: applying block to BDK wallet hash=0000016773c7f21ff9732bbb0871baeb4f23c07562b4c094533e81cb038e354d height=134963 tick=f31a4907fb444743a554c62298e5e373
 2025-04-28T05:00:49.803421Z ERROR bip300301_enforcer: app/main.rs:676: Received enforcer task error: CUSF enforcer task w/o mempool: failed connecting block to BDK chain
```

More logs:
```
2025-04-30T07:15:14.967350Z DEBUG sync_to_tip: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:870: connected block at height 23616: 00000215cf3bdf557b19b88151fba606a92677bc4374e0d983cf42fc8e4ece9c
 2025-04-30T07:15:14.968057Z DEBUG sync_to_tip: bip300301_enforcer_lib::wallet::cusf_block_producer: lib/wallet/cusf_block_producer.rs:53: Synced validator, syncing wallet.. tip_hash=00000215cf3bdf557b19b88151fba606a92677bc4374e0d983cf42fc8e4ece9c
 2025-04-30T07:15:14.968068Z DEBUG sync_to_tip: bip300301_enforcer_lib::wallet::cusf_block_producer: lib/wallet/cusf_block_producer.rs:75: Sending start signal to wallet task, kicking off periodic sync
 2025-04-30T07:15:14.968696Z  INFO grpc_server: tower_http::trace::on_response: /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.2/src/trace/on_response.rs:114: finished processing request latency=0 ms method=POST uri=http://localhost:50051/cusf.mainchain.v1.ValidatorService/GetChainInfo                                        request_id="req_58ab6a35d92a4573a52498c87ba2747c"
 2025-04-30T07:15:14.969610Z  WARN grpc_server: bip300301_enforcer_lib::server: lib/server.rs:155: Unable to convert miette::Report of type dyn miette::protocol::Diagnostic + core::marker::Send + core::marker::Sync to a meaningful tonic::Status:   × get balance: wallet not synced
  method=POST uri=http://localhost:50051/cusf.mainchain.v1.WalletService/GetBalance request_id="req_18aed1c58b214f83bcbc2fc62d6c7684" 
 2025-04-30T07:15:14.969643Z  INFO grpc_server: tower_http::trace::on_response: /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.2/src/trace/on_response.rs:114: finished processing request latency=0 ms status=2 method=POST uri=http://localhost:50051/cusf.mainchain.v1.WalletService/GetBalance                                    request_id="req_18aed1c58b214f83bcbc2fc62d6c7684"
 2025-04-30T07:15:14.969650Z ERROR grpc_server: tower_http::trace::on_failure: /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.2/src/trace/on_failure.rs:93: response failed classification=Code: 2 latency=0 ms method=POST uri=http://localhost:50051/cusf.mainchain.v1.WalletService/GetBalance                                     request_id="req_18aed1c58b214f83bcbc2fc62d6c7684"
 2025-04-30T07:15:15.033358Z  INFO bip300301_enforcer_lib::wallet::cusf_block_producer: lib/wallet/cusf_block_producer.rs:94: CUSF block producer: connecting block block_hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba
 2025-04-30T07:15:15.033418Z DEBUG bip300301_enforcer_lib::validator::cusf_enforcer: lib/validator/cusf_enforcer.rs:180: Storing header block_hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba
 2025-04-30T07:15:15.033540Z DEBUG bip300301_enforcer_lib::validator::cusf_enforcer: lib/validator/cusf_enforcer.rs:192: Connecting block block_hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba
 2025-04-30T07:15:15.033728Z DEBUG connect_block: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:740: updated current chain tip: 23617 block_hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba
 2025-04-30T07:15:15.033744Z  INFO bip300301_enforcer_lib::validator::cusf_enforcer: lib/validator/cusf_enforcer.rs:246: Accepted block block_hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba
 2025-04-30T07:15:15.035388Z  INFO handle_connect_block: bip300301_enforcer_lib::wallet::sync: lib/wallet/sync.rs:78: applying block to BDK wallet hash=000003041705ca37bcdec99e60a122e3249fc8c70bc07229381edabfe17372ba height=23617
 2025-04-30T07:15:15.036091Z ERROR bip300301_enforcer: app/main.rs:676: Received enforcer task error: CUSF enforcer task w/o mempool: failed connecting block to BDK chain
 2025-04-30T07:15:21.376250Z  INFO bip300301_enforcer: app/main.rs:539: Starting up bip300301_enforcer data_dir=/Users/bo/Library/Application Support/bip300301_enforcer log_path=/Users/bo/Library/Application Support/bip300301_enforcer/bip300301_enforcer.log
 2025-04-30T07:15:21.377144Z  INFO bip300301_enforcer: app/main.rs:548: Created mainchain client from options: user:*****@127.0.0.1:38332
 2025-04-30T07:15:21.634689Z  INFO bip300301_enforcer: app/main.rs:597: Connected to mainchain client network=signet blocks=25242
 2025-04-30T07:15:21.635838Z  INFO bip300301_enforcer_lib::validator::dbs: lib/validator/dbs/mod.rs:376: Created validator DBs in /Users/bo/Library/Application Support/bip300301_enforcer/validator/signet/signet.mdb
 2025-04-30T07:15:21.638870Z  INFO bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:285: Instantiating signet wallet data_dir=/Users/bo/Library/Application Support/bip300301_enforcer/wallet/signet database_path=/Users/bo/Library/Application Support/bip300301_enforcer/wallet/signet/wallet.sqlite.db
 2025-04-30T07:15:21.640304Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:131: creating electrum client electrum_url=drivechain.live:50001
 2025-04-30T07:15:21.806190Z  INFO bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:211: Created database connection to /Users/bo/Library/Application Support/bip300301_enforcer/wallet/signet/db.sqlite
 2025-04-30T07:15:21.807077Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:213: Ran migrations on /Users/bo/Library/Application Support/bip300301_enforcer/wallet/signet/db.sqlite
 2025-04-30T07:15:21.810100Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:317: found plaintext mnemonic, going straight to initialization
 2025-04-30T07:15:21.811843Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:232: Attempting load of existing BDK wallet
 2025-04-30T07:15:21.822039Z  INFO bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:252: Loaded existing BDK wallet
 2025-04-30T07:15:21.822165Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:330: wallet inner: wired together components wallet_initialized=true
 2025-04-30T07:15:21.822871Z DEBUG bip300301_enforcer_lib::wallet: lib/wallet/mod.rs:674: wallet sync task: starting interval=PT15S
 2025-04-30T07:15:21.823416Z  INFO bip300301_enforcer: app/main.rs:214: gRPC: enabling wallet service
 2025-04-30T07:15:21.823616Z DEBUG subscribe_sequence: cusf_enforcer_mempool::zmq: /Users/runner/.cargo/git/checkouts/cusf-enforcer-mempool-cb1614cfba1fef49/26bb6bd/lib/zmq.rs:287: Attempting to connect to ZMQ server... zmq_addr_sequence="tcp://127.0.0.1:29000"
 2025-04-30T07:15:21.823722Z DEBUG bip300301_enforcer: app/main.rs:232: Setting health status for service: cusf.mainchain.v1.ValidatorService 
 2025-04-30T07:15:21.824048Z DEBUG bip300301_enforcer: app/main.rs:232: Setting health status for service: cusf.mainchain.v1.WalletService
 2025-04-30T07:15:21.824055Z DEBUG bip300301_enforcer: app/main.rs:232: Setting health status for service: cusf.crypto.v1.CryptoService
 2025-04-30T07:15:21.824065Z  INFO bip300301_enforcer: app/main.rs:238: Listening for gRPC on 127.0.0.1:50051 with reflection
 2025-04-30T07:15:21.827952Z  INFO subscribe_sequence: cusf_enforcer_mempool::zmq: /Users/runner/.cargo/git/checkouts/cusf-enforcer-mempool-cb1614cfba1fef49/26bb6bd/lib/zmq.rs:292: Connected to ZMQ server zmq_addr_sequence="tcp://127.0.0.1:29000"
 2025-04-30T07:15:21.828164Z DEBUG subscribe_sequence: cusf_enforcer_mempool::zmq: /Users/runner/.cargo/git/checkouts/cusf-enforcer-mempool-cb1614cfba1fef49/26bb6bd/lib/zmq.rs:293: Attempting to subscribe to `sequence` topic... zmq_addr_sequence="tcp://127.0.0.1:29000"
 2025-04-30T07:15:21.828318Z  INFO subscribe_sequence: cusf_enforcer_mempool::zmq: /Users/runner/.cargo/git/checkouts/cusf-enforcer-mempool-cb1614cfba1fef49/26bb6bd/lib/zmq.rs:295: Subscribed to `sequence` zmq_addr_sequence="tcp://127.0.0.1:29000"
 2025-04-30T07:15:21.832459Z DEBUG sync_to_tip: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:804: Syncing header `000002e85ed83aa27f312094ae77ccc609b743b3be082779d6df00beabb6721e` -> `000002e85ed83aa27f312094ae77ccc609b743b3be082779d6df00beabb6721e`
 2025-04-30T07:15:21.833668Z DEBUG sync_to_tip: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:802: Syncing header #25305 `000000d9e58bd66e3b46e533d34a8d50d41da7661ba24468de32d2a1857c8020` -> `000002e85ed83aa27f312094ae77ccc609b743b3be082779d6df00beabb6721e`
 2025-04-30T07:15:21.834235Z DEBUG sync_to_tip: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:802: Syncing header #25304 `000002b4945069ef65cf07f59c3382ef6f492400954bc89f6d76ba5f93fb0df4` -> `000002e85ed83aa27f312094ae77ccc609b743b3be082779d6df00beabb6721e`
 2025-04-30T07:15:21.834662Z DEBUG sync_to_tip: bip300301_enforcer_lib::validator::task: lib/validator/task/mod.rs:802: Syncing header #25303 `000001c236edb6f30669bf47480fb22280fa164d92876c2d7e883be38182b252` -> `000002e85ed83aa27f312094ae77ccc609b743b3be082779d6df00beabb6721e`

```

### PR DESCRIPTION
**Pull request by torkelrogstad**
Closes #199 

Also handles chain splits. Note that there's no concept of "disconnecting a block" in BDK. Instead we're supposed to chug along with new block updates, and then BDK makes sure to keep track of all tips and automatically keep track of what's the best one.

### CODE REVIEW

File: lib/wallet/cusf_block_producer.rs [hunk 1]
```diff
@@ -91,28 +92,105 @@ impl CusfEnforcer for Wallet {
...
         // After the validator has accepted the block, we can handle it in the wallet.
-        let () = self
-            .inner
-            .handle_connect_block(block, block_height, block_info)
-            .await?;
+        //
+        // A few checks that need to happen:
+        // 1. Is the wallet tip part of the active chain?
+        // 2. Does the wallet have all the blocks up until the block we're trying to connect?
+        // .  If not, we have to iterate over the missing blocks and connect them first.
```
Comment (torkelrogstad) [inline lib/wallet/cusf_block_producer.rs:117]: Dot

File: lib/wallet/sync.rs [hunk 2]
```diff
@@ -87,53 +93,6 @@ impl WalletInner {
...
 
-        let bdk_tip_height = wallet_write.local_chain().tip().height();
-
-        // TODO: should really run the entire handle_connect_block logic here
-        if bdk_tip_height < block_height - 1 {
-            tracing::info!(
-                bdk_tip_height = bdk_tip_height,
-                block_height = block_height,
-                "BDK tip is behind newly received block, catching up"
-            );
```
Comment (torkelrogstad) [inline lib/wallet/sync.rs:98]: It's not clear to me why this is not working. On master, catching up multiple blocks at once in the sync leads to an error. On this PR, it works. Is it related to the `with_mut` stuff? I have to admit it's a bit over my head

Comment (torkelrogstad) [reply lib/wallet/sync.rs:98]: We're doing one commit for each block now, vs. only doing one commit for the entire batch. A single commit would be best - but not when it's not working. Probably OK for now, IMO.

**Review by Ash-L2L — APPROVED** [review]
