### PR TITLE
main: verify that Bitcoin Core REST server is enabled at startup

### LINKED ISSUE #209: Enforcer fails to start on macOS
At 10:30AM EST, the latest enforcer update is failing to start. I waited for bitcoind to sync first, and pressed the refresh button several times, but it’s the same error

I have also deleted everything drivechain related and tried multiple times

Tested on macOS and Linux

Image

### PR DESCRIPTION
**Pull request by torkelrogstad**
Closes #209.

Also make sure to give clearer error message if we're not able to reach Bitcoin Core at all.

### CODE REVIEW

File: app/main.rs [hunk 1]
```diff
@@ -546,17 +549,29 @@ async fn main() -> Result<()> {
             .map_err(|err| miette!("invalid mainchain REST URL `{raw_url}`: {err:#}"))?,
     );
 
+    let ts = tokio::time::Instant::now();
+    match mainchain_rest_client.get_chain_info().await {
+        Ok(_) => {
+            tracing::info!(
+                "verified mainchain REST server is enabled in {:?}",
+                ts.elapsed()
```
Comment (Ash-L2L) [inline app/main.rs:557]: Nit: This could be formatted using [jiff](https://docs.rs/jiff/latest/jiff/index.html) instead of using debug formatting

**Review by Ash-L2L — APPROVED** [review]
